name: build
on: [push]


jobs:
  ubuntu-mac:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        
    steps:
      - name: Checkout
        uses: actions/checkout@v2

# CMake 
      - name: install CMake  
        uses: lukka/get-cmake@latest       

# Qt install
#      - name: Install Qt
#        uses: jurplel/install-qt-action@v2

      - name: Install OpenCV (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install libopencv-dev

      - name: Install OpenCV (MacOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew update
          brew install opencv
          
      - name: Compile With CMake   
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build .
          
  Windows:
    runs-on:windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: install MSVC (Windows)
        uses: ilammy/msvc-dev-cmd@v1.4.1        
        
      - name: install CMake  
        uses: lukka/get-cmake@latest   
        
      - name: Install OpenCV (Windows)
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install opencv

      - name: Compile With CMake   
        run: |
          set OPENCV_DIR=C:\tools\opencv\build
          mkdir build
          cd build
          cmake ..
          cmake --build .
          
          
# Upload Result
#    - name: upload executable
#      uses: actions/upload-artifact@v2
#      with:
#        name: ${{matrix.os}}
#        path: |
#          ouputnamefile